# Generated by Django 4.2.6 on 2023-10-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('destination_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('destination_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('rating', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField(max_length=11)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
