# Generated by Django 4.2.6 on 2023-12-26 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0002_alter_review_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Destination.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 22, 7, 33, 119206)),
        ),
    ]
