# Generated by Django 4.2.6 on 2023-12-26 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0003_remove_review_user_id_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Destination.destinations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 22, 11, 59, 966426)),
        ),
    ]
